package rules;
import org.drools.DroolsDemo.PaymentOffer
global  org.drools.DroolsDemo.PaymentOffer my_payment_offer;
dialect  "mvel"


rule "offer for Paytm"
    when
        my_payment_offer: PaymentOffer(Channel=="paytm")
    then
        my_payment_offer.setDiscount(25);
    end

rule "Offer for PhonePe"
    when
        my_payment_offer: PaymentOffer(Channel=="phonepe")
    then
        my_payment_offer.setDiscount(20);
    end
rule "offer for GooglePay"
    when
        my_payment_offer: PaymentOffer(Channel=="googlepay")
    then
         my_payment_offer.setDiscount (25);
    end